version: '3.4'

services:
  ch.cena.swiper.backend.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
          - D:\images:/images
          - D:\pickup:/pickup
    environment:
      ConnectionStrings__PostgresConnection: 'Host=db;Database=cena;Username=cena;Password=yourStrong(!)Password'
      Hosting__HostingUri: 'http://localhost'
      Hosting__JwtIssuer: 'http://localhost'
      Hosting__JwtKey: 'Absolu3_Uns3cu53_K3y!'
      Hosting__JwtExpireDays: 120
      Migration__CreateProject: 'true'
      Migration__Migrate: 'true'