version: '3.4'

services:
  ch.cena.swiper.backend.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
         - /Users/tricktron/Xcode/cena/importedImages:/images
         - /Users/tricktron/Xcode/cena/imagePickup:/pickup
    environment:
      # - ConnectionStrings:SqlConnection=server=db;Initial Catalog=cena;Integrated Security=False;User ID=sa;Password=yourStrong(!)Password;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
        - ConnectionStrings:PostgresConnection=Host=db;Database=cena;Username=cena;Password=yourStrong(!)Password
        - Hosting:HostingUri=http://172.20.10.2
        - Hosting:JwtIssuer=http://172.20.10.2
        - Hosting:JwtKey=Absolu3_Uns3cu53_K3y!
        - Hosting:JwtExpireDays=120
        - Migration:CreateProject=true
        - Migration:Migrate=true