version: '3.4'

services:
    ch.cena.swiper.backend.api:
        image: ch.cena.swiper.backend.api
        build:
            context: .
            dockerfile: swiper.backend.api/Dockerfile
        # added port, in Dockerfile 80 is exposed which is mapped to 5000
        ports:
         - "80:80"
        # Mount your local path to /images
        volumes:
            - /images:/images
            - /pickup:/pickup
        # make the backend dependent on the sql server
        environment:
        # - ConnectionStrings:SqlConnection=server=db;Initial Catalog=cena;Integrated Security=False;User ID=sa;Password=yourStrong(!)Password;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
          - ConnectionStrings:PostgresConnection=Host=db;Database=cena;Username=cena;Password=yourStrong(!)Password
          - Hosting:HostingUri=https://cenaswiper.luethi.rocks
          - Hosting:JwtKey=secret #Exchange with actual JwtKey
          - Hosting:JwtIssuer=https://cenaswiper.luethi.rocks
          - Hosting:JwtExpireDays=5
          - Migration:CreateProject=false
          - Migration:Migrate=false
          - Migration:ProjectName=cena
          - Migration:ChallengeTypeName=cenaSwiper
          - Migration:ChallengeQuestion=Would you like to eat this here and now?
          - Migration:ChallengeAnswers=["Yes", "No", "No Food"]
        depends_on:
            - db
    # include the sql server into the container
    db:
        image: "postgres"
        environment:
            POSTGRES_USER: "cena"
            POSTGRES_PASSWORD: "yourStrong(!)Password"
