version: '3.4'

services:
  ch.cena.swiper.backend.api:
    image: chcenaswiperbackendapi
    build:
      context: .
      dockerfile: swiper.backend.api/Dockerfile
    # added port, in Dockerfile 80 is exposed which is mapped to 5000
    ports:
      - "80:80"
    # Mount your local path to /images
    volumes:
      - /images:/images
      - /pickup:/pickup
    # make the backend dependent on the sql server
    environment:
    # - ConnectionStrings__SqlConnection=server=db;Initial Catalog=cena;Integrated Security=False;User ID=sa;Password=yourStrong(!)Password;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False
      ConnectionStrings__PostgresConnection: 'Host=db;Database=cena;Username=cena;Password=yourStrong(!)Password'
      Hosting__HostingUri: 'https://cenaswiper.luethi.rocks'
      Hosting__JwtKey: 'secret' #Exchange with actual JwtKey
      Hosting__JwtIssuer: 'https://cenaswiper.luethi.rocks'
      Hosting__JwtExpireDays: 5
      Migration__CreateProject: 'false'
      Migration__Migrate: 'false'
      Migration__ProjectName: 'cena'
      Migration__ChallengeTypeName: 'cenaSwiper'
      Migration__ChallengeQuestion: 'Would you like to eat this here and now?'
      Migration__ChallengeAnswers: '["Yes", "No", "No Food"]'
    depends_on:
        - db
    # include the sql server into the container
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: 'cena'
      POSTGRES_PASSWORD: 'yourStrong(!)Password'